# Generated by Django 4.0.5 on 2022-06-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_cartitem_id_alter_product_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://cdn.onlinewebfonts.com/svg/img_231353.png'),
        ),
    ]
