# Generated by Django 4.0.5 on 2022-06-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
